export interface Mockup {
  name: string;
  src: string;
  href: string;
  id: number;
}

export const mockups: Mockup[] = [
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 1,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 2,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 3,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 4,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 5,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 6,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 7,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 8,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 9,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 10,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 11,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 12,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 13,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 14,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 15,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 16,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 17,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 18,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 19,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 20,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 21,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 22,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 23,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 24,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 25,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 26,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 27,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 28,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 29,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 30,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 31,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 32,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 33,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 34,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 35,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 36,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 37,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 38,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 39,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 40,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 41,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 42,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 43,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 44,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 45,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 46,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 47,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 48,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 49,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 50,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 52,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 52,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 53,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 54,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 55,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 56,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 57,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 58,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 59,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 60,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 61,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 62,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 63,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/1.jpg",
    id: 64,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/2.png",
    id: 65,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/3.jpg",
    id: 66,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/4.jpg",
    id: 67,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/5.jpg",
    id: 68,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/6.jpg",
    id: 69,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/7.jpg",
    id: 70,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/8.jpg",
    id: 71,
  },
  {
    name: "IMac Screen Mockup",
    href: "#",
    src: "/images/mockups/9.jpg",
    id: 72,
  },
];
